[package]
name = "bt-player"
version = "0.1.0"
edition = "2024"

[dependencies]
bluer = { version = "0.17.4", features = ["full"] }
tokio = { version = "1.47.1", features = ["full"] }
tokio-stream = "0.1.17"
zbus = { version = "5.11.0", features = ["tokio"] }
zvariant = "5.7.0"
